// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
var Xvfb = require('xvfb')
const fs = require('fs');

describe('Eternal Fury RU — проверка', function() {
  this.timeout(30000)
  let driver
  let vars
  let xvfb
  let site = "https://creagames.com/ru"
  before(async function() {
    var capabilities = {
      browserName: 'chrome',
      version: '76.0',
      enableVNC: true,
      enableVideo: false
    };
    driver = await new Builder()
    .usingServer('http://localhost:4444/wd/hub')
    .withCapabilities(capabilities)
    .setAlertBehavior()
    .build();
    vars = {}
  })
  after(async function() {
    //await shot('screen finish', driver)
    await driver.quit()
  })
  afterEach(function() {
    //shot(String(this.currentTest.title)+'. Отчёт', driver)
  })

it('Открыть портал', async function () {
  await driver.get(site)
  await driver.manage().window().setRect(1920,1080)
  await driver.manage().window().maximize()
})
it('Авторизоваться', async function () {
  await driver.wait(until.elementLocated(By.xpath("//*[.='Login']")),30001)
  await driver.wait(until.elementIsVisible(driver.findElement(By.xpath("//*[.='Login']"))),30001)
  await driver.findElement(By.xpath("//*[.='Login']")).click()
  await driver.wait(until.elementLocated(By.name("username")),30002)
  await driver.wait(until.elementIsVisible(driver.findElement(By.name("username"))),30001)
  await driver.findElement(By.name("username")).sendKeys("r.solodukhin@creagames.com")
  await driver.findElement(By.name("password")).sendKeys("123456qQ")
  await driver.findElement(By.name("password")).sendKeys(Key.ENTER)
  /*await driver.wait(until.elementLocated(By.css(".g-header_profile_data_name")),30003)
  await driver.wait(until.elementIsVisible(driver.findElement(By.css(".g-header_profile_data_name"))),30001)*/
})
describe('Проверка серверов', function() {
  let MAX_SERVERS = 8
  for(i = 1; i <= MAX_SERVERS; i++) {
    let link = site+"games/ef/server/"+i
    it('s'+i, async function() {
        await driver.get(link)
        await driver.wait(until.elementLocated(By.id('container')),10000)
        await driver.wait(until.elementIsVisible(driver.findElement(By.id('container'))),10000)
        await driver.wait(until.elementLocated(By.xpath('//*[@id="index"]')),30000)
        await driver.wait(until.elementIsVisible(driver.findElement(By.xpath('//*[@id="index"]'))),30001)
        await driver.findElement(By.xpath('//*[@id="index"]')).click()
      })
  }
})

});

async function shot(name, target) {
	target ? target : target = driver; //default param
	try{
		var fileName = String(name)+'.png';
		fs.writeFile(fileName, await target.takeScreenshot(), 'base64',
    function(){/*console.log("*** Screenshot "+fileName+' ***')*/});
		return true;
	}
	catch(error){
		throw new Error(error);
	}
};